### PR TITLE
Add more architectures.

### PR DESCRIPTION
**Pull request by hameerabbasi**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
@conda-forge-admin, please rerender

**Comment by hameerabbasi** [comment]
@conda-forge/help-ppc64le Any idea where the build is failing here?

**Comment by jayfurmanek** [comment]
Oh, it's because there are ppc64le nodes on travis-ci.org, and not in travis-ci.com. I notice the build on .org passed.
We're not entirely sure why sometimes it kicks off travis-ci.com runs as well, but this can be safely ignored, although its annoying for the status.

**Comment by isuruf** [comment]
You can ignore Travis.com status and only look at travis.org status. Also see https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests

**Pull request merged**
